name: camp_harmony_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.9.1
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  firebase_verify_token_dart: ^2.1.1
  dotenv: ^4.2.0


dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1

